/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package masseyhacksv3;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;
import javax.swing.JFrame;

/**
 *
 * @author Sterling
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScanButton = new javax.swing.JButton();
        ChangeModeButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        ChangeThemeButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Frame"); // NOI18N
        setResizable(false);

        ScanButton.setText("Scan");
        ScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScanButtonActionPerformed(evt);
            }
        });

        ChangeModeButton.setText("Change Size");
        ChangeModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeModeButtonActionPerformed(evt);
            }
        });

        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("TechSavvyGranny");
        Title.setAlignmentX(0.5F);

        ChangeThemeButton.setText("Change Theme");
        ChangeThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeThemeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChangeThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangeModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(ScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Title)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChangeThemeButton)
                        .addGap(72, 72, 72)
                        .addComponent(ChangeModeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(AboutButton))
                    .addComponent(ScanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScanButtonActionPerformed
        //String prg = "import sys";
        try {//as long as python exe path is working, it should work???
            File inputFile1 = new File("monitor.py");
            Scanner scanner = new Scanner(inputFile1);

            if (scanner.hasNextLine()) {
                String PythonAppPath = "C:\\Users\\Sterling\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe";
                
                String MonitorPath = "C:\\Users\\Sterling\\Desktop\\masseyhacksv\\monitor.py";
                Process p = Runtime.getRuntime().exec(PythonAppPath + " " + MonitorPath);
                System.out.println("yay");

            } else {
                System.exit(0);
            }

            /*
            
            mentor's edits
            
            Process p = Runtime.getRuntime().exec("C:\\Users\\Sterling\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe monitor.py");
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String ret = in.readLine();
            System.out.println("value is : " + ret);
             */
        } catch (IOException exception) {
            System.out.println(exception.getMessage());

        }
    }//GEN-LAST:event_ScanButtonActionPerformed
    int FileHolder = 0;
    private void ChangeModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeModeButtonActionPerformed
        Font XLFont = new Font ("Arial", Font.PLAIN, 52);
        Font largeFont = new Font("Arial", Font.PLAIN, 40);
        Font medFont = new Font("Arial", Font.PLAIN, 28);
        Font smallFont = new Font("Arial", Font.PLAIN, 14);

        if (FileHolder == 0) {
            ChangeModeButton.setFont(medFont);
            AboutButton.setFont(medFont);
            ChangeThemeButton.setFont(medFont);
            ScanButton.setFont(medFont);
            FileHolder = 5;
            Title.setFont (medFont);

        } else if (FileHolder == 1) {
            ChangeModeButton.setFont(largeFont);
            AboutButton.setFont(largeFont);
            ScanButton.setFont(largeFont);
            ChangeThemeButton.setFont(largeFont);
            FileHolder = 7;
            Title.setFont (largeFont);
        } else if (FileHolder == 2) {
            ChangeModeButton.setFont(smallFont);
            AboutButton.setFont(smallFont);
            ChangeThemeButton.setFont(smallFont);
            ScanButton.setFont(smallFont);
            FileHolder = 9;
            Title.setFont (smallFont);            

        }
        if (FileHolder == 5) {
            FileHolder = 1;
        }

        if (FileHolder == 7) {
            FileHolder = 2;
        }

        if (FileHolder == 9) {
            FileHolder = 0;
        }


    }//GEN-LAST:event_ChangeModeButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed

        this.dispose();//to close the current jframe

        new About().setVisible(true);
    }//GEN-LAST:event_AboutButtonActionPerformed
    int themeChooser = 0;
    private void ChangeThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeThemeButtonActionPerformed

        Color lightTheme = new Color(225, 225, 225);
        Color blueTheme = new Color(180, 190, 210);
        Color grayTheme = new Color(150, 150, 150);

        if (themeChooser == 0) {
            getContentPane().setBackground(lightTheme);
            themeChooser = 5;
        }
        if (themeChooser == 1) {
            getContentPane().setBackground(blueTheme);
            themeChooser = 7;
        }

        if (themeChooser == 2) {
            getContentPane().setBackground(grayTheme);
            themeChooser = 9;
        }
        if (themeChooser == 5) {
            themeChooser = 1;
            Title.setForeground(Color.BLACK);
        }
        if (themeChooser == 7) {
            themeChooser = 2;
            Title.setForeground(Color.BLACK);
        }
        if (themeChooser == 9) {
            themeChooser = 0;
            Title.setForeground(lightTheme);
        }
    }//GEN-LAST:event_ChangeThemeButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton ChangeModeButton;
    private javax.swing.JButton ChangeThemeButton;
    private javax.swing.JButton ScanButton;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
